version: '2'
services:
  web:
      image: rrcfesc/lamp:5.6
      ports:
          - "8098:80"
      volumes:
          - ./src:/var/www/html
          - ~/.ssh:/home/rioxygen/.ssh
          - ./apache_vhost:/etc/apache2/sites-available/
      environment:
        PHP_XDEBUG_ENABLED: 1
        XDEBUG_CONFIG: remote_host=192.168.1.58
      links:
          - mysql
      container_name: testing_web
  mysql:
      image: mysql:5.7
      volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/databasedata:/var/lib/mysql
      ports:
        - 3308:3306
      environment:
          - MYSQL_ROOT_PASSWORD=mysql
          - MYSQL_DATABASE=tutorial
      container_name: testing_db