version: '2'
services:
  web:
      image: apachephp:5.5
      ports:
          - "81:80"
      volumes:
          - ./:/var/www/html
          - ~/.ssh:/home/magento2/.ssh
          - ../apache_vhost:/etc/apache2/sites-available/
      environment:
        PHP_XDEBUG_ENABLED: 1
        XDEBUG_CONFIG: remote_host=192.168.1.58
        WEBSERVER_USER: www-data
        MAGENTO_USER: magento2
        CURRENT_USER_UID: 502
        MAGENTO_GROUP: 2000
      links:
          - mysql
      container_name: rioxygen-web
  mysql:
      image: mysql:5.7
      volumes:
      - ../mysql/config:/etc/mysql/conf.d
      - ../mysql/databasedata:/var/lib/mysql
      ports:
        - 3308:3306
      environment:
          - MYSQL_ROOT_PASSWORD=mysql
          - MYSQL_DATABASE=tutorial
      container_name: rioxygen-db